
POST http://localhost:8000/usuario
Content-Type: application/json

{
"nombre":"s",
"email":"s@gmail.com",
"contraseña":"456"
}


###
POST http://localhost:8000/cuentas
Content-Type: application/json

{
    "id_usuario":"1",
    "nombre":"Cuenta de Ahorros",
    "tipo":"Tarjeta",
    "saldo":25000
}

###


POST http://localhost:8000/
Content-Type: application/json

{
    "email":"per@gmail.com",
    "contraseña":"456"
}

