
POST http://localhost:8000/usuario
Content-Type: application/json

{
"nombre":"per",
"email":"per@gmail.com",
"contraseña":"456"
}
###


POST http://localhost:8000/
Content-Type: application/json

{
    "email":"per@gmail.com",
    "contraseña":"456"
}

